### ISSUE TITLE
Please update repo to include Firebase 8.1.0

### ISSUE THREAD

**Issue by snorrsi** [GameWorkstore/com.google.firebase.app#1]
dear owner,

It would be greatly appreciated if you could update your repo to include Firebase 8.1.0 for Unity as it was recently released.

Thanks again for this repo.

best regards,
Snorri

**Comment by john-rosa-playkids** [comment]
Hello @snorrsi ,

All repos were updated! Let me know if everything worked at your end, so I can close this issue,

Best

**Comment by snorrsi** [comment]
Hi @john-rosa-playkids ,

awesome.. Thanks.. just tried to use the Firebase 8.1.0 in Unity.

Seems Firebase Analytics (https://github.com/GameWorkstore/com.google.firebase.analytics) has not been updated.
Guess it's same issue as last time with insanely big file.

Can you look into it ?

Other packages that I use seem to installed fine at least. Haven't build yet but am going to in few minutes.

best regards,
Snorri

**Comment by john-rosa-playkids** [comment]
Hello @snorrsi , I just missed that package, now it's updated as well. Thank you for let me know!

The process of update a package is go through this file at main branch of each repo and update his version:
https://github.com/GameWorkstore/com.google.firebase.analytics/blob/main/.github/workflows/upmsync.yml
as it's a manual process, I may miss a package like that one from time to time ;D

Let me know if there is anything more I can help!
Otherwise you may close this issue,

Best
John

**Comment by snorrsi** [comment]
Hi @john-rosa-playkids ,

my build seems to be working fine with Firebase.

You should maybe create a shell script to automate the otherwise automated process.

Thanks for quick the update.

best regards,
Snorri
