### ISSUE TITLE
Version 10.6.0

### ISSUE THREAD

**Issue by heisarzola** [GameWorkstore/com.google.firebase.app#13]
An apology if this comes across as unreasonable, but I was just wondering when would this get updated to version 10.6.0.

The main reason being that other packages like remote config were already updated to that version, but cannot work until the core package (this one) is the same, at least on my testing.

**Comment by snorrsi** [comment]
Hi @heisarzola,

nope not at all. I updated allt the other packages the other day but had problem then updating the com.google.firebase.app package.
I asked @HanzaRu to look into it and don’t know if he has time to do it yet.
My apologies for this, if you really want to use the 10.6.0 version then you can until this is fixed use google .tgz version locally (only needed for firebase.app)
I also recommend always using version references instead of just #upm, use #10.3.0 (or 10.6.0) to get the exact version

**Comment by HanzaRu** [comment]
I have time to look at this issue on this Saturday, i think!

**Comment by HanzaRu** [comment]
Version 10.6.0 released!
